# Generated by Django 5.0.3 on 2024-08-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='Image',
            field=models.FileField(default='featur-1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
