# Generated by Django 5.0.3 on 2024-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pharmacy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='Email',
            field=models.CharField(max_length=100),
        ),
    ]
