# Generated by Django 5.0.3 on 2024-10-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pharmacy_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='image',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
