# Generated by Django 5.0.3 on 2024-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='expire',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
