# Generated by Django 5.0.3 on 2024-10-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_stock_description_stock_expire'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='status',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
